import { MigrationInterface, QueryRunner } from "typeorm";

export class FakeTitles1625401696326 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    queryRunner.query(`
        insert into quote (quote) values ('Through and Through (Na wylot)');
        insert into quote (quote) values ('Guter Junge');
        insert into quote (quote) values ('Rugrats in Paris: The Movie');
        insert into quote (quote) values ('No Direction Home: Bob Dylan');
        insert into quote (quote) values ('Gloomy Sunday (Ein Lied von Liebe und Tod)');
        insert into quote (quote) values ('The Hunters');
        insert into quote (quote) values ('Giants and Toys (Kyojin to gangu)');
        insert into quote (quote) values ('Hitch Hikers Guide to the Galaxy, The');
        insert into quote (quote) values ('Tess');
        insert into quote (quote) values ('Dangerous Ground');
        insert into quote (quote) values ('Guide, The (O Xenagos)');
        insert into quote (quote) values ('Payment Deferred');
        insert into quote (quote) values ('Becoming Chaz');
        insert into quote (quote) values ('Moolaadé');
        insert into quote (quote) values ('God''s Pocket');
        insert into quote (quote) values ('Intentions of Murder (a.k.a. Murderous Instincts) (Akai satsui)');
        insert into quote (quote) values ('Prom');
        insert into quote (quote) values ('Lovesick');
        insert into quote (quote) values ('The Humanoid');
        insert into quote (quote) values ('The Valley of Gwangi');
        insert into quote (quote) values ('Marmaduke');
        insert into quote (quote) values ('Class of 1999');
        insert into quote (quote) values ('Zombie Apocalypse');
        insert into quote (quote) values ('Carne de gallina (Chicken Skin)');
        insert into quote (quote) values ('Hearts in Atlantis');
        insert into quote (quote) values ('Christmas Party, The (Joulubileet)');
        insert into quote (quote) values ('Heart in Winter, A (Un coeur en hiver)');
        insert into quote (quote) values ('How I Got Into College');
        insert into quote (quote) values ('Taxi Hunter (Di shi pan guan)');
        insert into quote (quote) values ('Born to Fight (Kerd ma lui)');
        insert into quote (quote) values ('Snow Queen, The (Lumikuningatar)');
        insert into quote (quote) values ('Paulette');
        insert into quote (quote) values ('George of the Jungle');
        insert into quote (quote) values ('Grace of My Heart');
        insert into quote (quote) values ('Territories ');
        insert into quote (quote) values ('Piled Higher and Deeper');
        insert into quote (quote) values ('Vida precoz y breve de Sabina Rivas, La (Precocious and Brief Life of Sabina Rivas, The)');
        insert into quote (quote) values ('Skippy');
        insert into quote (quote) values ('Consuming Spirits');
        insert into quote (quote) values ('Taira Clan Saga, The (Shin heike monogatari)');
        insert into quote (quote) values ('Mist, The');
        insert into quote (quote) values ('Last Samurai, The');
        insert into quote (quote) values ('Vidal Sassoon: The Movie');
        insert into quote (quote) values ('Destroy All Monsters (Kaijû sôshingeki)');
        insert into quote (quote) values ('Doomed to Die');
        insert into quote (quote) values ('Tarnished Angels, The');
        insert into quote (quote) values ('Invisible Woman, The');
        insert into quote (quote) values ('Scooby-Doo');
        insert into quote (quote) values ('Touching the Void');
        insert into quote (quote) values ('Peter Pan');
        insert into quote (quote) values ('Faces of Death');
        insert into quote (quote) values ('Dragon Hunter');
        insert into quote (quote) values ('Darfur Now');
        insert into quote (quote) values ('Last Play at Shea, The');
        insert into quote (quote) values ('Associate, The');
        insert into quote (quote) values ('American Ninja 4: The Annihilation');
        insert into quote (quote) values ('Tentacles (Tentacoli)');
        insert into quote (quote) values ('Dragonworld');
        insert into quote (quote) values ('Frozen City (Valkoinen kaupunki) ');
        insert into quote (quote) values ('Arthur');
        insert into quote (quote) values ('My Father and the Man in Black');
        insert into quote (quote) values ('Bringing Down the House');
        insert into quote (quote) values ('Ultimate Gift, The');
        insert into quote (quote) values ('Marcello Mastroianni: I Remember Yes, I Remember (Marcello Mastroianni: mi ricordo, sì, io mi ricordo)');
        insert into quote (quote) values ('Hard Day''s Night, A');
        insert into quote (quote) values ('Star Trek');
        insert into quote (quote) values ('Last Waltz, The');
        insert into quote (quote) values ('That Championship Season');
        insert into quote (quote) values ('Report to the Commissioner');
        insert into quote (quote) values ('Rockaway');
        insert into quote (quote) values ('Voll Normaaal');
        insert into quote (quote) values ('Queen of the Amazons');
        insert into quote (quote) values ('Battleship');
        insert into quote (quote) values ('Handle with Care (a.k.a. Citizen''s Band)');
        insert into quote (quote) values ('Food (Jídlo)');
        insert into quote (quote) values ('Harold & Kumar Escape from Guantanamo Bay');
        insert into quote (quote) values ('What Lies Beneath');
        insert into quote (quote) values ('Natural Selection');
        insert into quote (quote) values ('Iron Ladies, The (Satree lek)');
        insert into quote (quote) values ('Lola and Billy the Kid (Lola + Bilidikid)');
        insert into quote (quote) values ('Hit List, The');
        insert into quote (quote) values ('Little Drummer Boy, The');
        insert into quote (quote) values ('Into the Forest of Fireflies'' Light');
        insert into quote (quote) values ('Remarkable Power');
        insert into quote (quote) values ('Cat''s Meow, The');
        insert into quote (quote) values ('Who Do I Gotta Kill?');
        insert into quote (quote) values ('Man of the West');
        insert into quote (quote) values ('American Me');
        insert into quote (quote) values ('Cyberbully');
        insert into quote (quote) values ('$ellebrity (Sellebrity)');
        insert into quote (quote) values ('Immediate Family');
        insert into quote (quote) values ('Mr. Turner');
        insert into quote (quote) values ('Jönssonligans största kupp');
        insert into quote (quote) values ('Felicity');
        insert into quote (quote) values ('Santo vs. las lobas');
        insert into quote (quote) values ('Employees'' Entrance');
        insert into quote (quote) values ('Waking Ned Devine (a.k.a. Waking Ned)');
        insert into quote (quote) values ('King Rat');
        insert into quote (quote) values ('Stretch');
        insert into quote (quote) values ('Book of Love');
        
        `);
  }

  public async down(_: QueryRunner): Promise<void> {}
}
